### ISSUE TITLE
Application is slow with a big number of users

### ISSUE THREAD

**Issue by reisfmb** [enonic/app-users#1045]
- [x] https://github.com/enonic/app-users/issues/1029
- [x] https://github.com/enonic/app-users/issues/1034
- [x] https://github.com/enonic/app-users/issues/1035
- [x] https://github.com/enonic/app-users/issues/1048
- [x] https://github.com/enonic/app-users/issues/1061
- [x] https://github.com/enonic/app-users/issues/1062
